In [1]:
 import numpy as np

In [2]:
import pandas as pd

In [3]:
import seaborn as sns

In [4]:
import matplotlib.pyplot as plt

In [5]:
import warnings

In [8]:
!pip install plotly

In [9]:
import plotly.offline as py

In [10]:
py.init_notebook_mode(connected=True)

In [11]:
import plotly.graph_objs as go

In [12]:
import plotly.tools as tls

In [13]:
from collections import Counter

In [14]:
import plotly.figure_factory as ff

In [16]:
from sklearn.ensemble import RandomForestClassifier

In [18]:
from sklearn.feature_extraction.text import CountVectorizer

In [19]:
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score

In [20]:
df=pd.read_csv("amazon_alexa.tsv", sep="\t")

In [21]:
df.head()

rating       date         variation  \
0       5  31-Jul-18  Charcoal Fabric    
1       5  31-Jul-18  Charcoal Fabric    
2       4  31-Jul-18    Walnut Finish    
3       5  31-Jul-18  Charcoal Fabric    
4       5  31-Jul-18  Charcoal Fabric    

                                    verified_reviews  feedback  
0                                      Love my Echo!         1  
1                                          Loved it!         1  
2  Sometimes while playing a game, you can answer...         1  
3  I have had a lot of fun with this thing. My 4 ...         1  
4                                              Music         1

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3150 entries, 0 to 3149
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   rating            3150 non-null   int64 
 1   date              3150 non-null   object
 2   variation         3150 non-null   object
 3   verified_reviews  3150 non-null   object
 4   feedback          3150 non-null   int64 
dtypes: int64(2), object(3)
memory usage: 123.2+ KB


In [23]:
df.describe()

rating     feedback
count  3150.000000  3150.000000
mean      4.463175     0.918413
std       1.068506     0.273778
min       1.000000     0.000000
25%       4.000000     1.000000
50%       5.000000     1.000000
75%       5.000000     1.000000
max       5.000000     1.000000

In [24]:
df.shape

(3150, 5)

In [28]:
df['variation'].nunique()

16

In [29]:
df['variation'].value_counts()

Black  Dot                      516
Charcoal Fabric                 430
Configuration: Fire TV Stick    350
Black  Plus                     270
Black  Show                     265
Black                           261
Black  Spot                     241
White  Dot                      184
Heather Gray Fabric             157
White  Spot                     109
White                            91
Sandstone Fabric                 90
White  Show                      85
White  Plus                      78
Oak Finish                       14
Walnut Finish                     9
Name: variation, dtype: int64

In [31]:
df.groupby('variation').agg({"rating":"mean"}).sort_values('rating', ascending = False).head()

rating
variation                             
Walnut Finish                 4.888889
Oak Finish                    4.857143
Charcoal Fabric               4.730233
Heather Gray Fabric           4.694268
Configuration: Fire TV Stick  4.591429

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3150 entries, 0 to 3149
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   rating            3150 non-null   int64 
 1   date              3150 non-null   object
 2   variation         3150 non-null   object
 3   verified_reviews  3150 non-null   object
 4   feedback          3150 non-null   int64 
dtypes: int64(2), object(3)
memory usage: 123.2+ KB


In [33]:
df["feedback"].value_counts().head()

1    2893
0     257
Name: feedback, dtype: int64

In [35]:
trace0 = go.Bar(
            x = df[df["feedback"]== 1]["feedback"].value_counts().index.values,
            y = df[df["feedback"]== 1]["feedback"].value_counts().values,
            name='Positive Feedback')


trace1 = go.Bar(
            x = df[df["feedback"]== 0]["feedback"].value_counts().index.values,
            y = df[df["feedback"]== 0]["feedback"].value_counts().values,
            name='Negative Feedback')

In [36]:
data = [trace0, trace1]
layout = go.Layout(yaxis=dict(title='Count'),
                   xaxis=dict(title='Feedback'),title='Feedback Distribution')

fig = go.Figure(data=data, layout=layout)
fig.data[0].marker.line.width = 4
fig.data[0].marker.line.color = "black"
fig.data[1].marker.line.width = 4
fig.data[1].marker.line.color = "black"
py.iplot(fig)

In [41]:
df1=df.drop(['date','rating'],axis=1)


In [43]:
df1.head()

variation                                   verified_reviews  \
0  Charcoal Fabric                                       Love my Echo!   
1  Charcoal Fabric                                           Loved it!   
2    Walnut Finish   Sometimes while playing a game, you can answer...   
3  Charcoal Fabric   I have had a lot of fun with this thing. My 4 ...   
4  Charcoal Fabric                                               Music   

   feedback  
0         1  
1         1  
2         1  
3         1  
4         1

In [47]:
variation_dummies=pd.get_dummies(df1['variation'],drop_first=True)

In [48]:
variation_dummies.head()

Black  Dot  Black  Plus  Black  Show  Black  Spot  Charcoal Fabric   \
0           0            0            0            0                 1   
1           0            0            0            0                 1   
2           0            0            0            0                 0   
3           0            0            0            0                 1   
4           0            0            0            0                 1   

   Configuration: Fire TV Stick  Heather Gray Fabric   Oak Finish   \
0                             0                     0            0   
1                             0                     0            0   
2                             0                     0            0   
3                             0                     0            0   
4                             0                     0            0   

   Sandstone Fabric   Walnut Finish   White  White  Dot  White  Plus  \
0                  0               0      0           0            0   
1                  0               0      0           0            0   
2                  0               1      0           0            0   
3                  0               0      0           0            0   
4                  0               0      0           0            0   

   White  Show  White  Spot  
0            0            0  
1            0            0  
2            0            0  
3            0            0  
4            0            0

In [50]:
df1.drop(['variation'], axis=1, inplace=True)

In [51]:
df1

verified_reviews  feedback
0                                         Love my Echo!         1
1                                             Loved it!         1
2     Sometimes while playing a game, you can answer...         1
3     I have had a lot of fun with this thing. My 4 ...         1
4                                                 Music         1
...                                                 ...       ...
3145  Perfect for kids, adults and everyone in betwe...         1
3146  Listening to music, searching locations, check...         1
3147  I do love these things, i have them running my...         1
3148  Only complaint I have is that the sound qualit...         1
3149                                               Good         1

[3150 rows x 2 columns]

In [52]:
df2=pd.concat([df1, variation_dummies], axis=1)

In [53]:
df2

verified_reviews  feedback  Black  Dot  \
0                                         Love my Echo!         1           0   
1                                             Loved it!         1           0   
2     Sometimes while playing a game, you can answer...         1           0   
3     I have had a lot of fun with this thing. My 4 ...         1           0   
4                                                 Music         1           0   
...                                                 ...       ...         ...   
3145  Perfect for kids, adults and everyone in betwe...         1           1   
3146  Listening to music, searching locations, check...         1           1   
3147  I do love these things, i have them running my...         1           1   
3148  Only complaint I have is that the sound qualit...         1           0   
3149                                               Good         1           1   

      Black  Plus  Black  Show  Black  Spot  Charcoal Fabric   \
0               0            0            0                 1   
1               0            0            0                 1   
2               0            0            0                 0   
3               0            0            0                 1   
4               0            0            0                 1   
...           ...          ...          ...               ...   
3145            0            0            0                 0   
3146            0            0            0                 0   
3147            0            0            0                 0   
3148            0            0            0                 0   
3149            0            0            0                 0   

      Configuration: Fire TV Stick  Heather Gray Fabric   Oak Finish   \
0                                0                     0            0   
1                                0                     0            0   
2                                0                     0            0   
3                                0                     0            0   
4                                0                     0            0   
...                            ...                   ...          ...   
3145                             0                     0            0   
3146                             0                     0            0   
3147                             0                     0            0   
3148                             0                     0            0   
3149                             0                     0            0   

      Sandstone Fabric   Walnut Finish   White  White  Dot  White  Plus  \
0                     0               0      0           0            0   
1                     0               0      0           0            0   
2                     0               1      0           0            0   
3                     0               0      0           0            0   
4                     0               0      0           0            0   
...                 ...             ...    ...         ...          ...   
3145                  0               0      0           0            0   
3146                  0               0      0           0            0   
3147                  0               0      0           0            0   
3148                  0               0      0           1            0   
3149                  0               0      0           0            0   

      White  Show  White  Spot  
0               0            0  
1               0            0  
2               0            0  
3               0            0  
4               0            0  
...           ...          ...  
3145            0            0  
3146            0            0  
3147            0            0  
3148            0            0  
3149            0            0  

[3150 rows x 17 columns]

In [54]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

In [55]:
alexa_countvectorizer = vectorizer.fit_transform(df['verified_reviews'])

In [56]:
alexa_countvectorizer.shape

(3150, 4044)

In [57]:
print(alexa_countvectorizer.toarray())


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [58]:
df2.drop(['verified_reviews'], axis=1, inplace=True)

In [59]:
df2.head()

feedback  Black  Dot  Black  Plus  Black  Show  Black  Spot  \
0         1           0            0            0            0   
1         1           0            0            0            0   
2         1           0            0            0            0   
3         1           0            0            0            0   
4         1           0            0            0            0   

   Charcoal Fabric   Configuration: Fire TV Stick  Heather Gray Fabric   \
0                 1                             0                     0   
1                 1                             0                     0   
2                 0                             0                     0   
3                 1                             0                     0   
4                 1                             0                     0   

   Oak Finish   Sandstone Fabric   Walnut Finish   White  White  Dot  \
0            0                  0               0      0           0   
1            0                  0               0      0           0   
2            0                  0               1      0           0   
3            0                  0               0      0           0   
4            0                  0               0      0           0   

   White  Plus  White  Show  White  Spot  
0            0            0            0  
1            0            0            0  
2            0            0            0  
3            0            0            0  
4            0            0            0

In [61]:
encoded_reviews = pd.DataFrame(alexa_countvectorizer.toarray())
encoded_reviews.head()

0     1     2     3     4     5     6     7     8     9     ...  4034  \
0     0     0     0     0     0     0     0     0     0     0  ...     0   
1     0     0     0     0     0     0     0     0     0     0  ...     0   
2     0     0     0     0     0     0     0     0     0     0  ...     0   
3     0     0     0     0     0     0     0     0     0     0  ...     0   
4     0     0     0     0     0     0     0     0     0     0  ...     0   

   4035  4036  4037  4038  4039  4040  4041  4042  4043  
0     0     0     0     0     0     0     0     0     0  
1     0     0     0     0     0     0     0     0     0  
2     0     0     0     0     0     0     0     0     0  
3     1     0     0     0     0     0     0     0     0  
4     0     0     0     0     0     0     0     0     0  

[5 rows x 4044 columns]

In [62]:
df3 = pd.concat([df2, encoded_reviews], axis=1)
df3.head()

feedback  Black  Dot  Black  Plus  Black  Show  Black  Spot  \
0         1           0            0            0            0   
1         1           0            0            0            0   
2         1           0            0            0            0   
3         1           0            0            0            0   
4         1           0            0            0            0   

   Charcoal Fabric   Configuration: Fire TV Stick  Heather Gray Fabric   \
0                 1                             0                     0   
1                 1                             0                     0   
2                 0                             0                     0   
3                 1                             0                     0   
4                 1                             0                     0   

   Oak Finish   Sandstone Fabric   ...  4034  4035  4036  4037  4038  4039  \
0            0                  0  ...     0     0     0     0     0     0   
1            0                  0  ...     0     0     0     0     0     0   
2            0                  0  ...     0     0     0     0     0     0   
3            0                  0  ...     0     1     0     0     0     0   
4            0                  0  ...     0     0     0     0     0     0   

   4040  4041  4042  4043  
0     0     0     0     0  
1     0     0     0     0  
2     0     0     0     0  
3     0     0     0     0  
4     0     0     0     0  

[5 rows x 4060 columns]

In [63]:
#Model Tuning and Result

In [64]:
x = df.drop(['feedback'], axis=1)
y = df['feedback']

In [67]:

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.25, random_state = 345)

In [80]:
rf_params = {"n_estimators" :[100,200,500,1000], 
             "max_features": [3,5,7], 
             "min_samples_split": [2,5,10,30],
             "max_depth": [3,5,8,None]}

rf_model = RandomForestClassifier(random_state = 357)

rf_cv_model = GridSearchCV(rf_model, rf_params, cv = 10, n_jobs = -1,verbose = 1).fit(x_train, y_train)

rf_tuned = RandomForestClassifier(**rf_cv_model.best_params_).fit(x,y)

Fitting 10 folds for each of 192 candidates, totalling 1920 fits


ValueError: 
All the 1920 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
192 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\niraj\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\niraj\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 345, in fit
    X, y = self._validate_data(
  File "C:\Users\niraj\anaconda3\lib\site-packages\sklearn\base.py", line 584, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "C:\Users\niraj\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 1106, in check_X_y
    X = check_array(
  File "C:\Users\niraj\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 879, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
  File "C:\Users\niraj\anaconda3\lib\site-packages\sklearn\utils\_array_api.py", line 185, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
  File "C:\Users\niraj\anaconda3\lib\site-packages\numpy\core\_asarray.py", line 102, in asarray
    return array(a, dtype, copy=False, order=order)
  File "C:\Users\niraj\anaconda3\lib\site-packages\pandas\core\generic.py", line 1993, in __array__
    return np.asarray(self._values, dtype=dtype)
  File "C:\Users\niraj\anaconda3\lib\site-packages\numpy\core\_asarray.py", line 102, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: could not convert string to float: '30-Jul-18'

--------------------------------------------------------------------------------
1728 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\niraj\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\niraj\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 345, in fit
    X, y = self._validate_data(
  File "C:\Users\niraj\anaconda3\lib\site-packages\sklearn\base.py", line 584, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "C:\Users\niraj\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 1106, in check_X_y
    X = check_array(
  File "C:\Users\niraj\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 879, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
  File "C:\Users\niraj\anaconda3\lib\site-packages\sklearn\utils\_array_api.py", line 185, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
  File "C:\Users\niraj\anaconda3\lib\site-packages\numpy\core\_asarray.py", line 102, in asarray
    return array(a, dtype, copy=False, order=order)
  File "C:\Users\niraj\anaconda3\lib\site-packages\pandas\core\generic.py", line 1993, in __array__
    return np.asarray(self._values, dtype=dtype)
  File "C:\Users\niraj\anaconda3\lib\site-packages\numpy\core\_asarray.py", line 102, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: could not convert string to float: '16-Jun-18'


In [81]:
 tuned = [rf_tuned]
print("Best Model Parameters and Scores:")
for i in tuned:
    score = cross_val_score(i, x_train, y_train, cv = 10).mean()
    print(i,"score:",score)

NameError: name 'rf_tuned' is not defined